---
title: "Group 13 UCSB"
author: "Eric Cole and Carleigh Osen"
date: "11/14/2021"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, messages = FALSE, results = "hide"}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
# Attach Packages
library(tidyverse)
library(here)
```
```{r, message = FALSE, warning = FALSE}
grad_data <- read_csv(here("data", "ucsb_grad_data.csv")) # Read in the data
```

```{r, message = FALSE, warning = FALSE}
ggplot(data = grad_data, aes(x = year_abbr, y = domestic_enrollment, fill = ethnicity)) +
  geom_col(position = "fill") + # Change to from number of individuals to proportion
  labs(x = "Enrollment Year",
       y = "Enrollment Ethnicity Percentage", # Change x- and y-axis labels
       caption = bold("Figure 1:") ~"Proportion of domestic graduate students enrolled at UCSB by ethnicity over time") + # Add figure caption
  ggtitle("UCSB domestic graduate student enrollment") + # Add figure title
  theme_minimal() + # Change theme 
  theme(plot.caption = element_text(hjust = 0.2)) # Adjust caption placement
  
```

